### ISSUE TITLE
Batch import and export

### ISSUE THREAD

**Issue by JeanFromentNILU** [Qiong-Yang/FastEI#6]
Dear developers,

thank you very much for this really nice software. I started using the GUI and have few questions:
1) Is it possible to import directly several compounds at once? Maybe in MGF format? (for now I am importing every compounds one by one with 1 CSV files per compound)
2) Is it possible to export a result summary for all the imported compounds?
3) I was wondering if in the spectra plot we could see the mass of the fragments? I have high-resolution data and would like to assess directly how good a fragment match is (are the predicted fragments using high-resolution data?)

Cheers
Jean

**Comment by zmzhang** [comment]
@JeanFromentNILU 
Dear Jean, 

Thank you for acknowledging our work. These suggestions are a good reference for the next edition of FastEI2.0. The updated software will include the ability to input multiple query spectra at once in MGF format or other formats, and support for exporting a matched result summary of all the imported compounds. In addition, the predicted spectra in our library have fragment m/z information. The predicted spectrum is EI-MS, which is low-resolution data. Currently, FastEI does not involve high-resolution spectral data. The direct matching effect of high-resolution data is expected to be suboptimal. It is needed to rebuild the high-resolution predicted spectrum library. On this basis, train the new word2vec model, construct an new HNSW index, and match the new library for compound identification.

Best regards,
Zhimin
